on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: export json and png
        uses: oliverlorenz/tiled-exporter-action@master
        with:
          export_json: true
          export_png: true
          tmx_file: "buero.tmx"
      
      - name: show files
        run: ls -la
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: .