on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_PAT }}
          repository: oliverlorenz/com_oliverlorenz
          event-type: cap-maps-was-changed

      # - name: export json and png
      #   uses: oliverlorenz/tiled-exporter-action@master
      #   with:
      #     export_json: true
      #     export_png: true
      #     tmx_file: "buero.tmx"
      
      # - name: show files
      #   run: ls -la
      
      # - name: show files
      #   run: ls -la workadventure-tiles
      
      # - name: show files
      #   run: git add .
      
      # - name: Deploy 🚀
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: .
      #     keep_files: true