on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: export json and png
        uses: oliverlorenz/tiled-exporter-action@master
        with:
          export_json: true
          export_png: true
          pattern: "*.tmx"
      
      - name: test
        run: ls -la /github/workspace